### PR TITLE
Get rid of jumpstart mess in car model

### PR DESCRIPTION
**Pull request by tombu**
The jumpstart method of the car model is a mess that has to be removed. The car model must work with the track model and can also look up future positions to calculate the rotation. No need for leaking out the business logic of the car into other parts of the application.

### CODE REVIEW

**Comment by stravid** [comment]
I looked into this and I have a hard time being sure whats the cause. Actually I found a fix to get rid of `jumpstart` but this means we have to use `0.0000000001` as "zero". And this can't be the solution, so @tombu @bmedicke we have to look into this together :)

**Comment by tombu** [comment]
### What this pull request does:
- moves car-update-logic from `GameController` into `Car`
- removes `jumpstart()` in car model
- extends `Car.moveTo` to take **two** positions instead of one

Instead of pushing the car a tiny little distance every frame (`jumpstart()` did that) we now pass to positions to `moveTo()`: first parameter is the position to move to, the second is just a little distance behind so the car has the correct orientation

These changes could cause some conflicts with the `feature/dangle` branch but we should care about it when it´s time to merge the latter.

**ATTENTION: please remember to close issue #76 while/after merging**

**Comment by DominikGuzei** [comment]
Thank you for the awesome fix! Pulled the code and everything works as expected! :+1: for merge

**Comment by stravid** [comment]
Should we merge?

**Pull request merged**
