### PR TITLE
PR: bug/snappy-buttons-with-energizejs

### PR DESCRIPTION
**Pull request by tombu**
This PR introduces `energize.js`. It makes our buttons/links react faster.
For detailed information: https://github.com/davidcalhoun/energize.js

### CODE REVIEW

**Comment by DominikGuzei** [comment]
hell yeah -> if it is already tested on ipad then merge!

**Comment by tombu** [comment]
It is tested - and the buttons are triggered really fast but it´s somehow slower. The iPad shows a loading circle immediately after touching a button - it didn´t do that before.

I assume there could be a connection to the Webrick server which is not really fast. I will try it with Thin or Unicorn to make sure these changes improve the game. :wink:

**Comment by stravid** [comment]
Good idea to test it with Thin!

**Comment by tombu** [comment]
I tried it with Thin but this couldn´t improve the result. I will close this PR.
In PR #197 I coded a manual way to speed up our interface.

**Pull request closed without merging**
