### PR TITLE
Pull Request: adds finish line

### PR DESCRIPTION
**Pull request by roboshoes**
Adds graphic for finish line. only in play screen mode though (intentially)

### CODE REVIEW

**Comment by stravid** [comment]
Looks good. Second opinion?

**Comment by tombu** [comment]
I´m content with the coding style. But I don´t really agree calling `#drawFinishLine` in `Game#start`. `drawFinishLine` should be a part of `drawTrack` like drawing the dashed line on the track because the finish line is also part of the track.

In addition I´m not certain about calling `drawTrack` in `Game#start` either. Shouldn´t it be enough to call it in `didInsertElement` (as it´s already done) and just set `path` on `TrackView` (in `Game#start`)?

Any opinions?

**Comment by roboshoes** [comment]
Let's make it a vote:

**Who thinks that needs to be changed:**
Mathias Paumgarten: _No_

**Comment by roboshoes** [comment]
Also I can tell you why I think it is not necessary:

It is not the views responsibility to be either bound to the Track or get the Track as a paramater at all; causes to many dependencies. I do admit on the other hand that `drawTrack`is not an approprate name if the view can decide to not draw it right away and does it when it can. It should be called `setPath` maybe. Allthough I find this to be a question of pure coding style/design.

**Comment by roboshoes** [comment]
Also: I don't think larger changes in architecture should be done in this pull request.

**Comment by DominikGuzei** [comment]
I agree with Tom that drawTrack and drawFinishLine should not be called from outside. Especially because we have no case where we need the track NOT to draw itself. The best way would be that the view observes its track model's path and react (re/draw) on changes. Beware that draw view extends track view, so also try the builder when you change that!

To your last point, i think we should do relatively small refactorings like that in feature branches like that. It's because now that you built drawFinishLine we discovered how to improve the code. Always leave the code better than you found it before (if there is a something to improve)

**Comment by roboshoes** [comment]
alright - alright. the majority has spoken. I'll get to it as soon as I can. Even thought I don't fully agree that the view should keep watching the path. 

but we figure out a way. Together we are **strong**

**Comment by roboshoes** [comment]
Here you go guys. Nice refactoring. Everybody should be happy!

**Comment by tombu** [comment]
A lot better. Almost perfect :wink2:

**Comment by roboshoes** [comment]
for the love of god ... can someone please merge that SOB!

**Pull request merged**
