### PR TITLE
Pull Request: chore/introduce configuration file

### PR DESCRIPTION
**Pull request by tombu**
Originally, I just wanted to switch to PostgreSQL in development and test. I then stumbled upon a little security issue. As our app is open source we shouldn´t check in the secret_token which we use in production. In Addition we also shouldn´t check in any license or API keys. I removed all existing ones and introduced a file (`config/configure.rb`) which loads the configuration from a YAML file (`config/configuration.yml`).

The `configuration.yml.template` file shows the structure of the real configuration file which is not checked into version control.

You can generate a new security_token using `ActiveSupport::SecureRandom.hex(64)` or `SecureRandom.hex(64)`(in the rails console).

### CODE REVIEW

**Comment by stravid** [comment]
Nice!

What has every single one of us to do in order to deploy / develop the slotcars application?

**Comment by tombu** [comment]
Everyone needs to copy `configuration.yml.template`, rename it to `configuration.yml` and insert values for the (currently) **three** keys/token. Generate a new secret_token using `ActiveSupport::SecureRandom.hex(64)` (or `SecureRandom.hex(64)`). Also, enter the other two keys.
I already set the keys for the production environment on Heroku (so nothing to do for you).

**Comment by stravid** [comment]
Travis fails: http://travis-ci.org/#!/stravid/slotcars/builds/1184625

Is there a way to solve this?

**Comment by tombu** [comment]
Aaaaah.. I don´t know why there are so many commits in here.. git told me to merge before letting me push the changes. The diff looks good.

**Comment by tombu** [comment]
Now the specs are green :smile:

**Comment by stravid** [comment]
Any reason to not merge?

**Comment by tombu** [comment]
I don´t know any... But I´m not allowed to ;)

**Pull request merged**
