### PR TITLE
Feature/highlight player highscore

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR adds highlighting of the current user highscore in the result screen.

### CODE REVIEW

**Comment by tombu** [comment]
Nice debug helper! If you didn´t know, Handlebars provides a simple 'log'  helper to log values ... for me, this was enough so far.

**Comment by tombu** [comment]
I´m not a fan of making the user ID public rather than writing IDs into the markup. As we have unique usernames we could equally identify the user by its name. But I also see, that using the ID is the simpliest solution.

**Comment by DominikGuzei** [comment]
@tombu I also really dislike this solution, but it's related to the solution of how we fetch highscores which is flawed. We should treat highscores more like models with relations etc. so that I could compare something else here.

In the current situation this is the easiest way to do it. I would not want to solve the highscores problem this weekend :wink:

**Comment by stravid** [comment]
This can be merged too! And I agree that we should look into highscores. But that's a big task (I want to look into other metrics too) so let's do it after monday!

**Pull request merged**
