### PR TITLE
Pull Request: chore/switch-to-postgres-in-development

### PR DESCRIPTION
**Pull request by tombu**
If you are extremly interested watch the Railscast (http://railscasts.com/episodes/342-migrating-to-postgresql) otherwise use my instructions.

**OPTION 1: Homebrew (MacOSX)**
You need Ruby 1.8.x (Homebrew does not support Ruby 1.9.x). If you didn´t remove it, Ruby is basically installed on every Mac. Otherwise, you can install Ruby 1.8.7 using RVM or rubyenv and symlink it to the system´s ruby (`usr/bin/ruby`):
`> ln -s /Users/your_username/.rvm/ruby-1.8.7-p352/bin/ruby /usr/bin/ruby`

`> brew install postgres`

If PostgreSQL is installed successfully, homebrew will show you further instructions.

Create DB cluster (which is owned by your default user):
`> initdb /usr/local/var/postgres`
Maybe you have to create the `var` directory by hand because of a `Permission denied` - I had to :/
If you want to create a seperate user, e.g. `_postgres`, read the comments on this page: http://www.postgresql.org/docs/9.0/interactive/postgres-user.html

To **start** the cluster enter:
pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start

To **stop** the cluster enter:
pg_ctl -D /usr/local/var/postgres stop -s -m fast

Or create a LaunchAgent (cluster is started every time you boot your system):
`mkdir -p ~/Library/LaunchAgents
cp /usr/local/Cellar/postgresql/9.1.3/homebrew.mxcl.postgresql.plist ~/Library/LaunchAgents/
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist`

**OPTION 2: PostgreSQL installer (MacOSX, Windows, Linux)**
Download the installer from: http://www.postgresql.org/download/
Take care of the user (I think `_postgres`) and the password. You have to insert these credentials in `config/configuration.yml`.

Now that the cluster is created and running, you need to run `bundle install` (removes sqlite gem and installs pg gem) and `rake db:create db:migrate db:seed` (to complete setup the database from ground)

If you are using your default system user you don´t need to fill 'postgres_username' and 'postgres_password' in the `config/configuration.yml`.

### CODE REVIEW

**Comment by stravid** [comment]
@bmedicke @DominikGuzei @MathiasPaumgarten Notify us as soon as you pulled the branch, followed the instructions and can confirm that everything works!

**Comment by stravid** [comment]
Works for me!

**Comment by roboshoes** [comment]
Ok dudes - thank you @tombu for a really good insight and description on all this. Workes like a charm on windows as well. There are a few thing you have to know though (same for Unix probably and thank you thank you @stravid for leading me to my _mistake_):

Before installing any of the gems Postrgres cluster has do be up and running. If you add pg with no postgres and install postgras later on, it won't **under no circumstances** work. It won't recognize the user.

Anyway. Installation complete!! Go merge!

**Comment by DominikGuzei** [comment]
Also updated to use pg! Had nearly no problems, only the native extension building needed a bundle config of --with-pg-config=/path/to/pg_config which was installed by the one click installer into /Library/Postgres ....

**Pull request merged**
