### PR TITLE
Feature/restart button

### PR DESCRIPTION
**Pull request by DominikGuzei**

### CODE REVIEW

**Comment by bmedicke** [comment]
Now we have performance issues toward the end of the track.

Profiling shows that a lot of time is spent in getPointAtLength().
drive() calls it up to four times per frame.

And we switched from ember-dev to ember.

**Comment by tombu** [comment]
Keeping perfomance issues in the back of my mind i think we´re ready for a merge :+1:
The performance issue should be handled as a 'chore'.

**Comment by stravid** [comment]
Did we have this performance issue also after adding the car crash user story?

I don't think so. But the problem is still gone if I disable this feature. Without the three additional calls to getPointAtLength the game is running smooth for me.

But it could also be due to the restart-button code, or the changes with the ember gems.

Does anyone have an idea how we could figure this out?

**Comment by stravid** [comment]
I don't think the performance issue is a chore since currently the game is not really playable.

**Comment by bmedicke** [comment]
I'm pretty sure that it's due to the 3 additional calls. I checked out 65e3 (adds routes to support browser reload) and it's already slow. This commit is both before the reload button code and the switch to ember.

edit:
The first commit with performance issues is e3f8(adds check for crashing in car controller).
The commit right before it (593c) is fine.

**Comment by tombu** [comment]
Ok!? I can´t reconstruct the performance issues. I just played about 10 minutes without page reload and the only thing i recognized was a minimal stammering of the car towards the end of the track.

On my machine the game is absolutely playable.

But: I agree that getting the car´s position 4 times per frame is 3 times too much :wink:

**Comment by stravid** [comment]
@bmedicke I just asked Chris and he says the same: When we played slotcars and tried to beat the others time there was no performance problem and the cars crashed.

So I guess I'm confused. Will try to forget this crazy shit until tomorrow..

Maybe we should really introduce a track model which handles the caching of the path... if that's really the issue.

**Comment by bmedicke** [comment]
Well, it all depends on how fast your computer is. 
At 593c it takes me 4 seconds to finish the track, at e3f8 6 seconds.

It's not really the position of the car that is calculated 4 times. 2 are for the current position (could be reduced to one) and 2 for the positions that the car's going to be at next (need those to check if the car crashes).

But I agree, let's merge it. :)

**Comment by DominikGuzei** [comment]
I wrote the car crash code with the upcoming 'rasterization' in mind -> that's why I didn't include any optimization for less calls to getPointAtLength which is terribly slow with Raphael. When we have the path as an array of coordinates those calls will be lightning fast since there is no computation needed. I don't think we should heavily optimize the code in car controller now but introduce the rasterization feature tomorrow and be happy again ;-)

:+1: lets merge!

**Comment by stravid** [comment]
Then let's merge!

**Pull request merged**
