### PR TITLE
PR: feature/build-screen-design

### PR DESCRIPTION
**Pull request by tombu**
This PR adds the new design to the BuildScreen. I had some conflicts with the styling of the sign up and login form (which already existed from the homescreen) but could (of course) handle them.

Instead of fetching the form field data with jQuery I did it the Ember way. With the `Ember.TextField` view you can pass a variable binding which work great and is more clean on the views.

The `AuthorizationView` now extends `TrackView` to have the track in the background like during the other steps.

### CODE REVIEW

**Comment by roboshoes** [comment]
as always - your PR is very clean (so I think). Merge!

**Comment by DominikGuzei** [comment]
The two buttons in the publication form are half-hidden for me (css problem) i only see the top edge of them (no text on buttons)

**Comment by DominikGuzei** [comment]
Another problem: when I try to publish a track as anonymous user and try to sign up i see two cancel buttons!

**Comment by DominikGuzei** [comment]
When I click redraw from any other state the info graphic with the finger is not fully shown

**Comment by DominikGuzei** [comment]
When I sign up in the build screen and try to publish my built track I get a fatal error:

```
Uncaught Error: <DS.StateManager:ember48200> could not respond to event setProperty in state rootState.loaded.created.inFlight. ember.js:16220
Ember.StateManager.Ember.State.extend.sendRecursively ember.js:16220
Ember.StateManager.Ember.State.extend.sendRecursively ember.js:16218
Ember.StateManager.Ember.State.extend.sendRecursively ember.js:16218
Ember.StateManager.Ember.State.extend.sendRecursively ember.js:16218
Ember.StateManager.Ember.State.extend.sendRecursively ember.js:16218
Ember.StateManager.Ember.State.extend.send ember.js:16198
DS.Model.Ember.Object.extend.send ember-data.js:2773
DS.Model.Ember.Object.extend.setProperty ember-data.js:2782
DS.attr ember-data.js:2959
Cp.set ember.js:3521
set ember.js:2490
Ember.Observable.Ember.Mixin.create.set ember.js:9782
Shared.Track.DS.Model.extend.setTitle track.js:89
```

**Comment by stravid** [comment]
First: Awesome!

Second: Could you please make it mergable? (Pull development into it)

Third: I think if we can't fix the sign up bug right now we should not show the Sign Up button until we fix it.

**Pull request merged**
