### PR TITLE
Chore/improve path cleaning

### PR DESCRIPTION
**Pull request by DominikGuzei**
Improves the cleaning algorithm in the builder to get rounder tracks with less problematic artifacts. It also removes the smooth method from path, since it is not used in the project anymore.

### CODE REVIEW

**Comment by stravid** [comment]
Looks good! Second opinion?

**Comment by tombu** [comment]
I like those 4 additions (an 83 deletions) :wink:

**Comment by DominikGuzei** [comment]
ouch -> der pull request kann anscheinend nicht automatisch gemergt werden - wie machen wirs dann?

**Comment by tombu** [comment]
by hand! but don´t ask me ;)

**Comment by stravid** [comment]
Click on the "i" symbol next to "This pull request cannot be automatically merged." and you have instructions how to do it!

**Pull request merged**
