### PR TITLE
Pull Request: Feature/testdrive mode

### PR DESCRIPTION
**Pull request by tombu**
Firstly I´m very sorry about letting this pull request again get that huge. In the end you will notice that it didn´t add that much logic. The biggest part of the nearly 300 deletions were just moved into other files.

What this PR does:
- splits up the **GameController** and moves basicc drive/game logic into the newly created `BaseGameController`. The `BaseGameController` handles the logic of setting `isTouchMouseDown`, creating and starting the `GameLoopController` and calling `update()` on the `Car`.
- adds a state manager (**BuildScreenStateManager**) to handle the different states of building. Currently I just implemented the `Drawing` and `Testing` states.
- adds a `TestDriveController` which extends `BaseGameController`. Besides the game logic it additionally handles button-click-actions that were recognized by `TestDriveView` (also new).
- adds a `TestDrive` class. This is quite similar to `Game` but I saw no way to use inheritance or mixins here. The `TestDrive` creates a `Car`, `TestDriveController`, `CarView`, `TrackView` and `TestDriveView` (has 2 dynamic views for `CarView` and `TrackView`). It then sets the `contentView` on the `buildScreenView` property.
- adds a `Controllable` mixin. This mixin can be applied to `TrackView`s and cares for the event binding of `touchMouseDown` / `touchMouseUp`. Those bindings can be controlled by the `carControlsEnabled` property. With this mixin, the `TrackView` can stay as basic as it is but can now be used as `DrawView`, `PlayTrackView` (with `Controllable`) and as `TrackView` (with `Controllable`).

As I´m still not really convinced about the linear building cycle I used the `goToState` method of the state manager to switch states instead of letting the state manager care about the next correct step. Also `goToState 'Testing'` is much more understandable than `send 'exit'`.

The content in `BaseGameController` and `Controllable` (and their spec files) are (almost) just copy-paste from `GameController` respectively `PlayTrackView`. So it´s not that important to review them :wink:.

**Note**: We need some buttons for 'Testing' to navigate to 'Editing' and navigate (back) to 'Drawing'!

Now I´m ready for getting fisted! :wink2:

Class Diagramm - BuildScreen

### CODE REVIEW

**Comment by stravid** [comment]
This looks awesome! I will take my time to take a stab at it :-)

**Comment by stravid** [comment]
@MathiasPaumgarten We need button graphics for clear (I suggest a refresh symbol), test drive (I suggest a symbolic car), save (I suggest a save symbol). All round and without text. Please make them and add them to this branch so @tombu can integrate them.

@tombu Please implement your way of navigation!

**Comment by stravid** [comment]
Actually also make the edit graphic please @MathiasPaumgarten :-)

**Comment by roboshoes** [comment]
I'll try to get to this as soon as possible guys!

**Comment by tombu** [comment]
Again a lot of changes ...
I already felt bad with the first 9 commits you can´t imagine how bad i feel now :(

What the last 7 commits do:
- The states `Rasterizing` and `Editing` are added to the `BuildScreenStateManager`. `Rasterizing` is a state that can´t be directly reached by the user but it is used as a intermediate step e.g. between `Editing` and `Testing`. The `Editing`-state was added because the `Drawing`-state is left immediately after the drawing is finished.
- The rasterization of the track and the view which belongs to it got separated from the `DrawController` and `DrawView` and is now in the `Rasterizer` and `RasterizationView`
- After a discussion last monday (with @stravid and @MathiasPaumgarten) we decided to give the 'lame navigation' a try.  Therefore all navigation buttons were moved into the `BuildScreenView` which updates the button states according to the possible transits (to other states) of the current state (of the `BuildScreenStateManager`).

**Comment by stravid** [comment]
The cancel button while rasterizing doesn't work on the iPad.

**Comment by roboshoes** [comment]
@tombu I added a PSD called buttons.psd in design/psd/button.psd

I think the refresh and the save button are nice but the other - ahhh - I don't know. For know you have graphics you can implement, but I might rework them. 

I didn't create PNGs yet because I didn't know where you want them, but I'm sure creating a PNG out of that is not challanging you on any level.

BTW: you find the graphics in the development branch, because that is where we kept all the design stuff so far. I didn't want to change that.

**Pull request merged**
