### PR TITLE
Feature/register

### PR DESCRIPTION
**Pull request by DominikGuzei**
Adds user registration via a button on the home screen and registration form handled by devise.

All other devise features are not yet enabled (login/logout and many others) since I thought it is cleaner to concentrate on each feature separately.

During the development of the feature I had to create a new button (register) and thus I added the project fonts and also created a button template psd file for future buttons.

list of changes:
- introduces devise
- adds user model that is linked with devise and is registerable with username and email
- adds register button on home screen
- changes route local links to only use a tags with class .js-route for HTML 5 push state
- moves the slotcars application into its own layout to separate "normal" pages like registration
- adds button template for easy creation of new buttons
- adds projects fonts to design folder to be easily accessable for all

### CODE REVIEW

**Comment by roboshoes** [comment]
I've seen it work on the iPad and I want it. MERGE!

**Comment by stravid** [comment]
Is there a reason behind introducing a separate slotcars layout?

Great work!

**Comment by DominikGuzei** [comment]
there are two reasons:
- We don't need the javascript / styles of the application
- For the slotcars game we introduces styles that deactivate touch selection in css. This deactivated input fields and it was impossible in webkit based browsers (chrome / safari) to enter text.

**Comment by stravid** [comment]
Alright, thanks for explaining!

**Pull request merged**
