### PR TITLE
Pull Request: feature/play-from-user-highscore

### PR DESCRIPTION
**Pull request by stravid**
Now you can play a track directly from the user highscores!

I removed all link styles, so it's probably not obvious you can click them. Should / can we change this?

### CODE REVIEW

**Comment by DominikGuzei** [comment]
yeah for the ipad it should be obvious that those are links which are clickable

**Comment by tombu** [comment]
I agree with dominik. But I have no concrete idea how it should look like.

**Comment by DominikGuzei** [comment]
in the first step i would just make the track title in a different color (blue?) and show the pointer cursor to indicate that its clickable. To be honest, in the next days most visitors will use a computer and not the ipad anyway.

**Comment by tombu** [comment]
Changes are OK. I trust you about the color of the link ;) :+1: merge!

**Pull request merged**
