### PR TITLE
PR: chore/refactor-game-and-testdrive – base TestDrive and Game on identical structure

### PR DESCRIPTION
**Pull request by tombu**
The `TestDrive` class was introduced by the the PR #121 and has a structure similar to the one of the `Game` class but they use different objects. As discussed with @DominikGuzei those two classes should be on the same base. So to speak a `Game` that is configurable. The factory pattern could be useful here. Currently I have no detailed thoughts just mentioned it to remember.

### CODE REVIEW

**Comment by tombu** [comment]
Here it is .. a super awesome PR :wink:
I completely removed `TestDriveController` and `TestDriveView` as they are no longer needed (they didn´t have a real purpose at the time I started refactoring).

@DominikGuzei and I discussed that it is a good idea if we pass a `Car` each time so I moved the default car configuration inside the `Car` to avoid code duplication.
Based on the `TestDrive` I created the `BaseGame` (most of it could remain). To close the gap to `Game` I introduced several initialization steps (`_createGameController`, `_createViews`, `_applyMixins`, `_appendViews`).
The `BaseGame` creates a `BaseGameController`, a `TrackView`, a `CarView` and a `BaseGameViewContainer` which allows setting dynamicViews.

The `Game` extends `BaseGame` and overrides `_createGameController` to create a `GameController` (I didn´t use a mixin here because the `GameController` has a too important role in my opinion). In addition it creates and appends a `ClockView` and a `GameView`.

Also, I couldn´t back off and had to adjust variable names in `ClockView` and remove unused methods in `GameView`.

There´s almost no new functionality so most of the spec are just c&p ... it just looks ugly :/

**Comment by stravid** [comment]
Crazy shit. Looks good :-)

**Comment by stravid** [comment]
This blocks my zoom view feature, could one of you please review this @DominikGuzei @MathiasPaumgarten @bmedicke?

**Comment by DominikGuzei** [comment]
dafür bekommst du ein sternchen ins Heft!

**Pull request merged**
