### PR TITLE
Pull Request: feature/ghost

### PR DESCRIPTION
**Pull request by stravid**
Please look at it. Try it(!). Report bugs. And make suggestions how we can make the code look and work good. The current solution is pretty rough.

There are no specs due to the reasons mentioned above and because I'm super stressed out over the ghost :-(

### CODE REVIEW

**Comment by tombu** [comment]
Bug: Ghost moves to wrong position after finish.
Reproduce: beat the ghost!

After crossing the finish line the ghost slows down correctly but as soon as the car stands still, the ghost is set to a position outside the window.

**Comment by tombu** [comment]
Bug: Ghost does no longer move correctly after you crossed the finish-line
Reproduce: make sure to see the ghost when you cross the finish-line!

The ghost just stays on the position that it had at the time when you crossed the finish-line and is just moved like your car.
This does not happen if the ghost already stands still when you finish.

**Comment by DominikGuzei** [comment]
code wise I would move most of the stuff that landed in game controller into the ghost or user model (loading ghost etc.)

**Comment by stravid** [comment]
I implemented the versus graphics. I would say the ghost is ready. Any objections? @tombu @DominikGuzei @MathiasPaumgarten

**Comment by DominikGuzei** [comment]
really cool versus graphics changes! I will merge now :-D

**Pull request merged**
